### ISSUE TITLE
return HASC code

### ISSUE THREAD

**Issue by burritojustice** [geocodeearth/ge#7]
Include the HASC code when reverse geocoding.

**Comment by missinglink** [comment]
Hey @burritojustice 👋 what are you looking for exactly?
Is the 2 character ISO 3166 country code enough?

**Comment by missinglink** [comment]
It seems we are already pulling in HASC concordances from WOF

eg: [looking at this issue from back in 2017](https://github.com/whosonfirst-data/whosonfirst-data/issues/581) we have that record here: https://pelias.github.io/compare/#/v1/place?ids=whosonfirst%3Acounty%3A1092044937

The `properties.addendum.concordances["hasc:id"]` value is set to `"MM.BA.BG"`:

<img width="269" alt="Screenshot 2022-05-13 at 20 53 31" src="https://user-images.githubusercontent.com/738069/168353217-84d20a38-552d-4d1a-85ed-a2affb8297ad.png">

The issue is that this batch geocoding tool doesn't map *any* of the `addendum` properties to CSV rows.

It's pretty trivial to implement, but how do you see it working exactly?

the easiest option would probably be to encode the whole concordances object as JSON and stuff it in a new column named "concordances", presumably there would be a lot of quoting and escaping going on so it wouldn't be very pretty to the eye.

another option would be to try and put every concordance in its own column, this could result in many columns and I'm pretty sure the current code defines all the columns up-front and can't easily handle the introduction of dynamic columns at runtime due to its streaming interface.

**Comment by burritojustice** [comment]
> Hey @burritojustice 👋 what are you looking for exactly?
> Is the 2 character ISO 3166 country code enough?

Unfortunately ISO 3166 and 3166-2 are not granular enough — we need to be able to categorize locations at the county level.

**Comment by missinglink** [comment]
Could you please test out https://github.com/geocodeearth/ge/pull/8 and see if that resolves your issue?

```bash
# globally install the 'ge' tool based on the 'user-specified-fields' branch
[sudo?] npm i -g "https://github.com/geocodeearth/ge.git#user-specified-fields"
```

you'll need to add two new command-line flags to extract the additional field:

```bash
-c 'hasc' -s 'properties.addendum.concordances["hasc:id"]'
```

[documentation here](https://github.com/geocodeearth/ge/tree/user-specified-fields#additional-response-columns)

**Comment by burritojustice** [comment]
I see the new column in the csv but it's not getting populated for counties where I've confirmed there are `hasc` codes. Pretty sure I'm running #8 but maybe there's some npm magic I'm missing?
